name: executives
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
 
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  googleapis_auth: ^1.4.1
  http: ^1.1.2
  injectable: ^2.3.2
  intl: ^0.19.0
  page_transition: ^2.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^21.2.3
  upi_payment_qrcode_generator: ^1.4.0
  url_launcher: ^6.2.3
  qr_flutter: ^4.1.0
    


dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
   

fonts:
  - family: montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Montserrat-Black.ttf
        weight: 900


# cupertino_icons,
# bloc_concurrency,
# flutter_bloc,
# get_it,
# freezed_annotation,
# injectable,
# dartz,
# cloud_firestore,
# firebase_auth,
# firebase_core,
# firebase_messaging,
# firebase_storage,
# cached_network_image,
# page_transition,
# intl,
# bloc,
# bot_toast,
# equatable,
# shared_preferences,
# shimmer,
# googleapis_auth,
# http,
# pinput,
# syncfusion_flutter_datepicker,
# url_launcher,


# #####################

# injectable_generator,
# build_runner,
# freezed,