name: executives
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2

  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  dartz: ^0.10.1
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.12.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
 
  firebase_storage: ^11.2.6
 
  cached_network_image: ^3.3.0
  page_transition: ^2.1.0
  intl: ^0.18.1
  bloc: ^8.1.2
  bot_toast: ^4.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  pinput: ^3.0.1
  syncfusion_flutter_datepicker: ^23.1.43

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
   

fonts:
  - family: montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Montserrat-Black.ttf
        weight: 900
